plugins {
    id "io.spring.dependency-management" version "1.1.7"
    id 'java'
    id 'jacoco'
    id 'com.gradleup.shadow' version '9.3.1'
    id "com.github.spotbugs" version "6.4.8"
    id 'maven-publish'
    id("io.freefair.lombok") version "9.5.0"
}

apply from: 'project-properties.gradle'

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.5.10"
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = "https://build.shibboleth.net/nexus/content/repositories/releases/" }

    if (!releaseMode) {
        maven {
            url = 'https://jitpack.io'
        }
    }
}

dependencies {
    if (releaseMode) {
        implementation 'com.epam.reportportal:service-api'
        annotationProcessor('com.epam.reportportal:service-api') {
            exclude group: 'org.springframework.modulith', module: 'spring-modulith-apt'
        }
    } else {
        implementation 'com.github.reportportal:service-api:b6fe35f3df'
        annotationProcessor('com.github.reportportal:service-api:b6fe35f3df') {
            exclude group: 'org.springframework.modulith', module: 'spring-modulith-apt'
        }
    }
    implementation 'jakarta.annotation:jakarta.annotation-api:3.0.0'
    implementation 'org.springframework.security:spring-security-oauth2-client'
    implementation 'org.springframework.security:spring-security-config'
    implementation 'org.springframework:spring-webmvc'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

test {
    useJUnitPlatform()
    maxParallelForks = 1
    testLogging {
        events = ['failed']
        exceptionFormat = 'short'
    }
    reports {
        junitXml.required.set(true)
    }
}

build.dependsOn jacocoTestReport

artifacts {
    archives shadowJar
}

sourceSets {
    main {
        resources
                {
                    exclude '**'
                }
    }
}

jar {
    from("src/main/resources") {
        into("/resources")
    }
    from("ui/build") {
        into("/resources")
    }
    doFirst {
        manifest {
            attributes(
                    "Class-Path": configurations.compileClasspath.collect { it.getName() }.join(' '),
                    "Plugin-Class": "${pluginClass}",
                    "Plugin-Id": "${pluginId}",
                    "Plugin-Name": "${pluginName}",
                    "Plugin-Version": "${project.version}",
                    "Plugin-Provider": "${provider}",
                    "Plugin-License": "${license}",
                    "Plugin-Description": "${project.description}",
                    "Plugin-Documentation": "${documentation}",
                    "Plugin-Metadata-isIntegrationsAllowed": "${isIntegrationsAllowed}",
                    "Plugin-Binary-Data-main": "${mainBinaryData}"
            )
        }
    }
}

shadowJar {
    from("src/main/resources") {
        into("/resources")
    }
    configurations = [project.configurations.compileClasspath]
    zip64 = true
    minimize()
    // dependencies {    }
}

tasks.register('plugin', Jar) {
    getArchiveBaseName().set("plugin-${pluginId}")
    into('classes') {
        with jar
    }
    into('lib') {
        from configurations.compileClasspath
    }
    archiveExtension.set('zip')
}

tasks.register('assemblePlugin', Copy) {
    from plugin
    into pluginsDir
}

tasks.register('assemblePlugins', Copy) {
    dependsOn subprojects.assemblePlugin
}

spotbugsMain {
    ignoreFailures = true
    reports {
        html {
            required = true
        }
    }
}

javadoc.enabled = false
