version=1.0.0
description=EPAM Report Portal. Github auth plugin.
pluginId=github
pluginClass=com.epam.reportportal.extension.github.GithubPlugin
pluginName=GitHub Auth Plugin
provider=ReportPortal
license=Apache 2.0
documentation=https://reportportal.io/docs/plugins/authorization/GitHubAuthorization
isIntegrationsAllowed=true
mainBinaryData=main.js
