version=1.0.0
description=EPAM Report Portal. GitHub auth plugin.
pluginId=github
pluginClass=com.epam.reportportal.extension.github.GitHubPlugin
pluginName=GitHub Auth
provider=ReportPortal
license=Apache 2.0
documentation=https://reportportal.io/docs/plugins/authorization/GitHubAuthorization
isIntegrationsAllowed=true
mainBinaryData=main.js
